### ISSUE TITLE
Function to save trained parameters?

### ISSUE THREAD

**Issue by tybalex** [google-deepmind/recurrentgemma#1]
I was able to fine-tune recurrentgemma-2b-it, using Jax, by loading the model with `recurrentgemma.load_parameters()` following this [colab example](https://colab.research.google.com/github/google-deepmind/recurrentgemma/blob/main/colabs/fine_tuning_tutorial_jax.ipynb). But once I have a trained model/checkpoint, I can't find anything yet to save the params. I would guess it should be something like https://github.com/google-deepmind/recurrentgemma/blob/main/examples/simple_run_jax.py? Although this one doesn't work for me.

**Comment by Nush395** [comment]
Hi @tybalex, thanks for the issue! You can use `orbax` to save the checkpoint as described in this example - https://flax.readthedocs.io/en/latest/guides/training_techniques/use_checkpointing.html#with-orbax. 

This is the method that is used in the `simple_run_jax` example. What is the issue you're encountering with using that?

**Comment by Nush395** [comment]
You can in general save any pytree with orbax checkpoint. 

We've added a simple util for saving that should be useful to you - https://github.com/google-deepmind/recurrentgemma/blob/main/recurrentgemma/jax/utils.py#L25.

**Comment by botev** [comment]
@tybalex the function `GriffinConfig.from_flax_params_or_variables` expects to be passed either direct dict of parameters, or as nush did a dict that has a key "params". In your case the parameters under "model" key so you need to do smth like:
```
Params =  recurrentgemma.load_parameters("/content/recurrentgemma-2b-it", "single_device")["model"]
config = recurrentgemma.GriffinConfig.from_flax_params_or_variables(params)
model = recurrentgemma.Griffin(config)
```

Or save directly the `trained_params`

**Comment by tybalex** [comment]
Thank you both for the help. `save directly the trained_params` works for me !
