### ISSUE TITLE
[Question] Does recurrentgemma use the same tokenizer as gemma? 

### ISSUE THREAD

**Issue by Mooler0410** [google-deepmind/recurrentgemma#7]
In the paper, it's mentioned that:

> Like Gemma, we use a subset of the SentencePiece tokenizer (Kudo and Richardson, 2018),
with a vocabulary size of 256k tokens.

If not, how different are they? One is from another by extending the vocab or both are trained from scratch?

Thanks!

**Comment by Nush395** [comment]
Hi, thanks for your question. That's correct RecurrentGemma uses the same tokenizer as Gemma.

**Comment by botev** [comment]
Closing this as the question has been answered.
